oswaldhoundekon/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', views.index,name='homepage'),
    path('privacy', views.privacy,name='privacy_policy'),
    path('contact', views.contact,name='contact'),
]

urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

projects/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='all_projects'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.project_details, name='details'),
]

projects/models.py
import random as r
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from slugify import slugify



# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 200)
    
    def __str__(self):
        return self.name
    


class Contributor(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField(default='default_contributor.png')
    
    def __str__(self):
        return self.name
    
    
class Tag(models.Model):
    tag = models.CharField(max_length=100)
    
    def __str__(self):
        return self.tag
    
    
class Project(models.Model):
    def main_image_upload(instance, filename):
        #this should return the os.path.join('media/projects/userxx')
        new_pp = '{}_{}_{}.{}'.format(instance.client,instance.title,'main_image','jpg')
        return 'projects/{}/{}'.format(instance.title, new_pp)
    
    def head_image_upload(instance, filename):
        #this should return the os.path.join('media/projects/userxx')
        new_pp = '{}_{}_{}.{}'.format(instance.client,instance.title,'head_image','jpg')
        return 'projects/{}/{}'.format(instance.title, new_pp)
    
    title = models.CharField(max_length=100)
    summary = models.TextField()
    client = models.CharField(max_length= 50)
    category = models.ManyToManyField(Category)
    date = models.DateField()
    projectMainColor = models.CharField(max_length=20, blank=True)
    website = models.URLField(max_length= 50, blank=True)
    contributors = models.ManyToManyField(Contributor)
    mainImage = models.ImageField(upload_to = main_image_upload, blank = True)
    headImage = models.ImageField(upload_to = head_image_upload, blank = True)
    slug = models.SlugField(default='link')
    tags = models.ManyToManyField(Tag, blank=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    

  
class ProjectImages(models.Model):
    def image_upload(instance,filename):
        #this should return the os.path.join('media/projects/userxx')
        #how to generate a random integer number within a range?
        num = r.randint(0, 10)
        myfilename = '{}_{}.{}'.format(instance.project.title,num,'jpg')
        return 'projects/{}/{}'.format(instance.project.title, myfilename)
    
    
    name = models.CharField(max_length =50)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    thumb = models.ImageField(upload_to = image_upload,blank = True)
    
    def __str__(self):
        return self.name
    

    
  
#this is to handle the deletion action on video model
#in case an object is deleted, the file associated with it is too
@receiver(pre_delete, sender = ProjectImages)
def ProjectImages_delete(sender, instance, **kwargs):
    #we pass False so that FileField does not save the model
    instance.thumb.delete(False)
    
    
@receiver(pre_delete,sender=Project)
def Project_delete(sender, instance, **kwargs):
    #we pass False so that FileField does not save the model
    instance.mainImange.delete(False)


testimonies/models.py
from django.db import models

# Create your models here.

oswaldhoundekon/views.py
from django.shortcuts import render
from django.http import HttpResponse
from projects.models import Project
from django.core.mail import send_mail

def index(request):
    works = Project.objects.all()[:7]
    return render(request, 'index.html', {'works':works, 'range':range(4), 'page_title':'Home'})


def privacy(request):
    context = {'page_title':'Privacy Policy'}
    return render(request, 'privacy.html', context)

def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        company_name = request.POST['company-name']
        email = request.POST['email']
        service = request.POST['service']
        project_details = request.POST['project-detail']
        
        message = "This is a mail from {}, whose company name is {}. They're requesting a {} service. Here is the project details:\n{}".format(name,company_name,service,project_details)
        send_mail(
            service,
            message,
            email,
            ['oswaldhoundekon@gmail.com']
        )
        context = {'page_title':'Contact','server_response':name}
        return render(request, 'contact.html', context)
    else:
        context = {'page_title':'Contact'}
        return render(request, 'contact.html', context)

projects/views.py
from unicodedata import category
from django.shortcuts import render
from .models import *


# Create your views here.
def projects(request):
    project_list = Project.objects.all().order_by('?')
    categories_list = Category.objects.all()

    context = {'projects':project_list, 'page_title':'Projects', 'categories':categories_list}
    return render(request, 'projects/projects.html', context)


def project_details(request, slug):
    project = Project.objects.get(slug=slug)
    all_projects = Project.objects.all()
    next_project = None
    previous_project = None
    #defining next and previous projects
    #if this is not he last project in the data set (this is for the next project)
    if not project.id == all_projects[len(all_projects)-1].id:
        next_project = all_projects[list(all_projects).index(project) + 1]
        
    #if this not the first project of the data set
    if not project.id == all_projects[0].id:
        previous_project = all_projects[list(all_projects).index(project) - 1]
    
    
    #get instances of projectImages
    projectImages = ProjectImages.objects.filter(project=project.id).order_by('?')
    #get a of their thumbs
    thumbs = [i.thumb for i in projectImages]
    
    contributors = Contributor.objects.filter(project = project.id)
    #contribs = ', '.join([str(i) for i in Contributor.objects.filter(project = project.id)])
    category = ', '.join([str(a) for a in Category.objects.filter(project = project.id)])
    tags = ', '.join([str(a) for a in Tag.objects.filter(project = project.id)])
    
    #this variable is just to simplify the reder code
    context = {
        'page_title':project.title,
        'project':project,
        'projectImages':thumbs, 
        'contributors':contributors, 
        'categories':category,
        'tags':tags,
    }
    
    if next_project is not None:
        context['next_project'] = next_project
    if previous_project is not None:
        context['previous_project'] = previous_project
    
    return render(request, 'projects/project_details.html', context)

testimonies/views.py
from django.shortcuts import render

# Create your views here.

projects/templates/projects/project_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="img-shower pt-md-5 w-100">
        <img class="w-100" src="{{project.mainImage.url}}" alt="">
    </div>
    <div class="container-fluid">
        <div class="container py-5" id="project-details">
            <div class="row justify-content-center-align-items-center">
                <div class="col-12 col-lg-4">
                    <div class="row pb-5">
                        <div class="">
                            <p class="display-6 playfair border-bottom d-inline-block" data-name="{{project.title}}" id='project-name'>{{project.title}}</p>
                        </div>
                        <div class="py-3">
                            <div class="row">
                                <div class="col-6">
                                    <p class="fs-4 playfair m-0">Client</p>
                                    <p class="fs-6">{{project.client}}</p>
                                </div>
                                <div class="col-6">
                                    <p class="fs-4 playfair m-0">Categories</p>
                                    <p class="fs-6">{{categories}}</p>
                                </div>
                                <div class="col-6">
                                    <p class="fs-4 playfair m-0">Date</p>
                                    <p class="fs-6">{{project.date}}</p>
                                </div>
                                <div class="col-6">
                                    <p class="fs-4 playfair m-0">Contributors</p>
                                    <div>
                                        {% for contributor in contributors %}
                                        <span class="my-tool-tip" data-bs-placement="bottom" title="{{contributor.name}}">
                                            <img style="max-width:30px; border:1px solid white; border-radius:100px!important;" src="{{contributor.picture.url}}" class="rounded float-start" alt="{{contributor.name}}">
                                        </span>
                                            {% endfor %}
                                    </div>    
                                    {% comment %} <p class="fs-6">{{contributors}}</p> {% endcomment %}
                                </div>
                            </div>
                            <div class="my-2">
                                <p class="my-3 mx-1 d-inline rounded-pill px-3 py-1 project-tag">{{tags}}</p>
                            </div>
                            
                        </div>
                        <div class=""><a href="{% url 'projects:all_projects' %}" class="btn bg-orange text-white">Back To Projects</a></div>
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <p class="fs-3 fw-bold" data-aos="fade-up" data-aos-delay="100">Project Summary</p>
                    <p>{{project.summary|linebreaks}}</p>
                    {% if project.website != '' %}
                        <a href={{project.website}} class="text-orange">Visit their website <i class="bi bi-arrow-right"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="pb-5 container" id="imagery">
            <div id="head_img" class="w-100" ata-aos="fade-up" data-aos-delay="100" >
                <img src="{{ project.headImage.url }}" class="rounded" alt="{{ project.title }}">
            </div>
            <div class="image-container">
                {% for projectImage in projectImages %}
                    <img data-aos="fade-up" data-aos-delay="100" class="rounded proj-img" src="{{ projectImage.url }}" alt="{{ projectImage.name }}">
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container rounded py-5 px-1 p-md-5 d-flex" data-mouse-down-at-y='0' data-mouse-down-at-x='0' id='next-project'>
            <div class="py-md-3 row w-100">
                <div class="col d-flex justify-content-start">
                    {% if previous_project %}
                        <a id="previous_project_link" href="{% url 'projects:details' slug=previous_project.slug %}" class="btn btn-outline-danger btn-sm"><i class="bi bi-arrow-left"></i> <span class="d-none d-md-inline">See previous project</span></a>
                    {% endif %}
                </div>
                <div class="col d-flex justify-content-end">
                    {% if next_project %}
                        <a id="next_project_link" href="{% url 'projects:details' slug=next_project.slug %}" class="btn btn-outline-danger btn-sm"><span class="d-none d-md-inline">See next project</span> <i class="bi bi-arrow-right"></i></a>
                    {% else %}
                        <p class="btn btn-outline-orange m-0">New project coming...</p>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
    <style>
        #next-project{
            background-image: url("{{project.mainImage.url|safe}}");
            background-size:cover;
            background-repeat: no-repeat;
            background-position: center center;
        }
    </style>


    {% comment %} view image box {% endcomment %}
    <div id="view-image" class="py-5 m-0 d-none">
        <span class="my-tool-tip" data-ba-position="bottom" title="Close">
            <i class="bi bi-x text-orange fs-1" id="close-icon"></i>
        </span>
        <img id="view-image-img" class="w-100 rounded" src="" alt="">
    </div>


    <script>
        var nextProjectLink = document.querySelector('#next_project_link');
        var nextProjectImg =  `{{ next_project.mainImage.url|safe }}`;
        var previousProjectLink = document.querySelector('#previous_project_link');
        var previousProjectImg = `{{previous_project.mainImage.url|safe}}`;
        var currentImg = `{{project.mainImage.url|safe}}`;

        console.log(nextProjectImg);
        console.log(previousProjectImg);
        console.log(currentImg);


        nextProjectLink.addEventListener('mouseenter',function(){
            document.querySelector('#next-project').style.backgroundImage = `url(${nextProjectImg})`;
        });
        previousProjectLink.addEventListener('mouseenter',function(){
            document.querySelector('#next-project').style.backgroundImage = `url(${previousProjectImg})`;
        });
        nextProjectLink.addEventListener('mouseleave',function(){
            document.querySelector('#next-project').style.backgroundImage = `url(${currentImg})`;
        });
        previousProjectLink.addEventListener('mouseleave',function(){
            document.querySelector('#next-project').style.backgroundImage = `url(${currentImg})`;
        });
    </script>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid py-5">
    <div class="container pt-md-3 text-center">
        <p class="h1 cormorant">My <br> <span class="text-orange">Work</span></p>
        <img class="pb-3" width="80" src="{% static 'scratch.svg' %}" alt="">
        <div class="py-3">
            {% for category in categories %}
                <a class="btn btn-outline fs-sm-6 fs-4 text-light badge">{{category.name}}</a>
            {% endfor %}
        </div>
        <div class="py-5" id="imagery">
            <div class="image-container">
                {% for project in projects %}
                        <a href="{% url 'projects:details' slug=project.slug %}"><img class="rounded proj" src="{{ project.mainImage.url }}" alt=""></a>
                {% endfor %}    
            </div>      
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
<section class="hero container-fluid py-5">
    <canvas class="d-none d-md-block w-100"></canvas>
    <div class="hero-next h-100 py-5 row align-items-center">
        <div class="col">
            <div class="container">
                <div class="row justify-content-center align-items-center">
                    <div class="col-md-3 d-none d-md-block">
                        <div class="p-3">
                            <p class="" data-aos="fade-right" data-aos-delay="2200">I am a freelance graphic designer and software engineer who creates
                                best-in-class logo design and brand identity.</p>
                        </div>
                        <div class="py-5 d-none d-lg-block"></div>
                    </div>
                    <div class="col-md-6 text-center py-5">
                        <h1 class="display-2 fw-bolder playfair">I am</h1>
                        <h1 class="display-2 fw-bolder playfair"><span class='text-orange'>O</span>swald <span class='text-orange'>H</span>oundekon</h1>
                        <img width="300" class="text-danger" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="3200" src="{% static 'scratch.svg' %}" alt="">
                    </div>
                    <div class="col-md-3" data-aos="fade-left"  data-aos-delay="2400">
                        <div class="py-5 d-none d-lg-block"></div>
                        <p class=" d-md-none">I am a freelance graphic designer and software engineer who create
                            best-in-class logo design and brand identity.</p>
                        <p class="">Educating people about their brand stories, identity, design and business.
                            Through creative excellence, I aim at transforming brands into sustainable success
                            stories that inspire customers and employees.</p>
                        <div>
                            <a class="text-white" href="{% url 'contact' %}">Let's Talk</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="container-fluid py-5 px-0">
    <div class="container text-center">
        <p class="h1 cormorant">I am proud to have worked <br> with these amazing brands</p>
        <img width="80" src="{% static 'scratch.svg' %}" alt="">
    </div>
    <div class="marquee-container d-flex flex-row w-100 mt-5">
        <div class="marquee w-100 col-10">
            <div class="row w-100 py-2 align-items-center">
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'kamelo.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'dalch_sun.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'maras.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'blueside.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'acklam.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'bendownbutik.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'uzima-homes.svg' %}" alt="">
                </div>
            </div>
        </div>
        <div class="marquee w-100 col-12">
            <div class="row w-100 py-2 align-items-center">
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'kamelo.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'dalch_sun.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'maras.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'blueside.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'acklam.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'bendownbutik.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'uzima-homes.svg' %}" alt="">
                </div>
            </div>
        </div>
        
    </div>
    <div class="marquee-container d-flex flex-row w-100 mt-5">
        <div class="marquee2 w-100 col-10">
            <div class="row w-100 py-2 align-items-center">
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'kamelo.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'dalch_sun.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'maras.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'blueside.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'acklam.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'bendownbutik.svg' %}" alt="">
                </div>
            </div>
        </div>
        <div class="marquee2 w-100 col-12">
            <div class="row w-100 py-2 align-items-center">
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'kamelo.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'dalch_sun.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'maras.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'blueside.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'acklam.svg' %}" alt="">
                </div>
                <div class="col d-flex justify-content-center p-0">
                    <img width="50%" src="{% static 'bendownbutik.svg' %}" alt="">
                </div>
            </div>
        </div>
        
    </div>
</section>

<section class="container-fluid py-5">
    <div class="container text-center">
        <p class="h1 cormorant">Working hard since 2018</p>
        <img width="80" src="{% static 'scratch.svg' %}" alt="">
        <div class="row justify-content-center align pt-5 px-md-5">
            <div class="container w-md-100 w-lg-75">
                <div class="row justify-content-center align-items-center">
                    <div class="col-12 col-md d-flex justify-content-start justify-content-md-end">
                        <img class="w-50" data-aos="fade-right" src="{% static 'header-background.png' %}" alt="img-oswaldhoundekon">
                    </div>
                    <div class="col-12 col-md text-start">
                        <div class="w-100 here_i_am_p">
                            <p class="my-3" data-aos="fade-up" data-aos-delay="100">A leading Graphic Designer and software engineer who specialises in logo
                                design, hand lettering, brand identity and UI/UX design.</p>
                            <p class="my-3" data-aos="fade-up" data-aos-delay="200">With more than 5 years of experience, I have produced high-quality content
                                for lots of clients, ranging from already well established businesses to SMEs and
                                small-scale start-ups.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<section class="container-fluid py-5 services">
    <div class="container text-center">
        <p class="h1 cormorant">Services I offer</p>
        <img width="80" src="{% static 'scratch.svg' %}" alt="">
        <div class="row justify-content-center align-items-center py-5">
            <div class="col-5 m-2">
                <p class="playfair fs-3" data-aos="zoom-in">Full Brand Identity</p>
            </div>
            <div class="col-5 m-2">
                <p class="playfair fs-3" data-aos="zoom-in" data-aos-delay="50">Logo Design</p>
            </div>
            <div class="col-5 m-2">
                <p class="playfair fs-3" data-aos="zoom-in" data-aos-delay="100">Web Design</p>
            </div>
            <div class="col-5 m-2">
                <p class="playfair fs-3" data-aos="zoom-in" data-aos-delay="150">Ux/Ui Design</p>
            </div>
        </div>
    </div>
</section>

<section class="container-fluid py-5">
    <div class="container text-center">
        <p class="h1 cormorant">My work</p>
        <img width="80" src="{% static 'scratch.svg' %}" alt="">
        <div class="py-5" id="">
            <div class="image-container">
                {% comment %} {% for work in works %}
                        <a data-aos="fade-down" href="{% url 'projects:details' slug=work.slug %}">
                            <img class="rounded proj" src="{{ work.mainImage.url }}" alt="">
                        </a>
                {% endfor %}     {% endcomment %}

                <ul class="list-group playfair">
                    {% for work in works %}
                        <a data-aos="fade-down" class="link-underline-opacity-0" href="{% url 'projects:details' slug=work.slug %}">
                            <li class="bg-transparent text-light fs-1 py-4 list-group-item d-flex justify-content-between align-items-start">
                                <p>{{work.title}}</p>
                                <span><i class="bi bi-eye"></i></span>
                            </li>
                        </a>
                    {% endfor %}  
                    
                </ul>
            </div>      
        </div>
    </div>
</section>

<section class="container-fluid py-5 testimonies">
    <div class="container text-center">
        <p class="h1 cormorant">My clients' feedback is important to me</p>
        <img width="80" src="{% static 'scratch.svg' %}" alt="">

        <div class="row justify-content-center align-items-center py-5">
            {% for i in range %}
                <div class="col-6 p-1" data-aos="fade-down">
                    <div class="card text-start bg-transparent rounded">
                        <div class="card-body rounded">
                            <div class="user d-flex flex-column flex-sm-row pb-2">
                                <div class="user-dp me-2">
                                    <img src="{% static 'header-background.png' %}" alt="">
                                </div>
                                <div class="user-info">
                                    <h5 class="mb-0">Chadly Ngoy</h5>
                                    <small>Entrepreneur</small>
                                </div>
                            </div>
                            <p>Really good, you have saved our business! I made bacck the purchase price in just 48
                                hours!
                                man, this thing is getting better and better as I learn more about it.</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}
